---
- name: Are you sure?
  pause:
    seconds: 20
    prompt: |

      ============================================================
        DANGER - abort if anyone else has access to this server!
      ============================================================

      Your private SSH key should never be copied to an insecure
      location.

      ------------------------------------------------------------

- name: Ensure .ssh directory exists for users
  file:
    dest: "{{ item.ssh_dir | default('/home/' + item.user + '/.ssh') }}"
    mode: 0700
    owner: "{{ item.user }}"
    group: "{{ item.group | default(item.user) }}"
    state: directory
  with_items: "{{ ssh_identity_remote_users }}"

- name: Copy identity files
  copy:
    src: "{{ ssh_identity_local_ssh_dir }}/{{ ssh_identity_local_ssh_key_private }}"
    dest: "{{ item.ssh_dir | default('/home/' + item.user + '/.ssh') }}/{{ item.key_file_name_private | default(ssh_identity_local_ssh_key_private) }}"
    mode: 0600
    owner: "{{ item.user }}"
    group: "{{ item.group | default(item.user) }}"
  with_items: "{{ ssh_identity_remote_users }}"

- name: Copy public files
  copy:
    src: "{{ ssh_identity_local_ssh_dir }}/{{ ssh_identity_local_ssh_key_public }}"
    dest: "{{ item.ssh_dir | default('/home/' + item.user + '/.ssh') }}/{{ item.key_file_name_public | default(ssh_identity_local_ssh_key_public) }}"
    mode: 0600
    owner: "{{ item.user }}"
    group: "{{ item.group | default(item.user) }}"
  with_items: "{{ ssh_identity_remote_users }}"

- name: "~ fin ~"
  pause:
    seconds: 0
    prompt: |

      ============================================================
                     MANUAL STEPS MAY BE REQUIRED
      ============================================================

      You may need to log on to the server and ssh-add identities.

      You may need to restart the sshd service.

      ------------------------------------------------------------

#- name: Add password reader utility file for use in ssh-add
#  template:
#    src: printpass.sh.j2
#    dest: "{{ ssh_identity_remote_ssh_dir }}/printpass.sh"
#    mode: 0777
#    owner: "{{ ssh_identity_remote_owner }}"
#    group: "{{ ssh_identity_remote_group }}"
#
#- name: Add password adder utility file for use in ssh-add
#  template:
#    src: addpass.sh.j2
#    dest: "{{ ssh_identity_remote_ssh_dir }}/addpass.sh"
#    mode: 0777
#    owner: "{{ ssh_identity_remote_owner }}"
#    group: "{{ ssh_identity_remote_group }}"
#
#- name: Add SSH identity to the agent
#  raw: "{{ ssh_identity_remote_ssh_dir }}/addpass.sh"
#
#- name: Remove password utility files
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - "{{ ssh_identity_remote_ssh_dir }}/printpass.sh"
#    - "{{ ssh_identity_remote_ssh_dir }}/addpass.sh"